language: java
jdk:
  - openjdk11
services:
  - postgresql
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
env:
  - DB_USER=postgres DB_URI=postgresql://localhost:5432/ DB_PASSWORD=